# Form implementation generated from reading ui file 'frame_profesion.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(592, 402)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Frame)
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Frame)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.tfCodigo = QtWidgets.QLineEdit(parent=Frame)
        self.tfCodigo.setEnabled(True)
        self.tfCodigo.setMaximumSize(QtCore.QSize(300, 26))
        self.tfCodigo.setObjectName("tfCodigo")
        self.gridLayout.addWidget(self.tfCodigo, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=Frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tfNombre = QtWidgets.QLineEdit(parent=Frame)
        self.tfNombre.setEnabled(True)
        self.tfNombre.setMaximumSize(QtCore.QSize(300, 26))
        self.tfNombre.setObjectName("tfNombre")
        self.gridLayout.addWidget(self.tfNombre, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCrearProfesion = QtWidgets.QPushButton(parent=Frame)
        self.btnCrearProfesion.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnCrearProfesion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCrearProfesion.setObjectName("btnCrearProfesion")
        self.horizontalLayout.addWidget(self.btnCrearProfesion)
        self.btnBuscarProfesion = QtWidgets.QPushButton(parent=Frame)
        self.btnBuscarProfesion.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnBuscarProfesion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnBuscarProfesion.setObjectName("btnBuscarProfesion")
        self.horizontalLayout.addWidget(self.btnBuscarProfesion)
        self.btnActualizarProfesion = QtWidgets.QPushButton(parent=Frame)
        self.btnActualizarProfesion.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnActualizarProfesion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnActualizarProfesion.setObjectName("btnActualizarProfesion")
        self.horizontalLayout.addWidget(self.btnActualizarProfesion)
        self.btnEliminarProfesion = QtWidgets.QPushButton(parent=Frame)
        self.btnEliminarProfesion.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnEliminarProfesion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEliminarProfesion.setObjectName("btnEliminarProfesion")
        self.horizontalLayout.addWidget(self.btnEliminarProfesion)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.tfCodigo, self.tfNombre)
        Frame.setTabOrder(self.tfNombre, self.btnCrearProfesion)
        Frame.setTabOrder(self.btnCrearProfesion, self.btnBuscarProfesion)
        Frame.setTabOrder(self.btnBuscarProfesion, self.btnActualizarProfesion)
        Frame.setTabOrder(self.btnActualizarProfesion, self.btnEliminarProfesion)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Profesion"))
        self.label_4.setText(_translate("Frame", "Nombre"))
        self.label_5.setText(_translate("Frame", "Código"))
        self.btnCrearProfesion.setText(_translate("Frame", "Crear Profecion"))
        self.btnBuscarProfesion.setText(_translate("Frame", "Buscar Profecion"))
        self.btnActualizarProfesion.setText(_translate("Frame", "Actualizar Profecion"))
        self.btnEliminarProfesion.setText(_translate("Frame", "Eliminar Profecion"))
