# Form implementation generated from reading ui file 'frame_bitacora.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(774, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=Frame)
        self.label_4.setStyleSheet("QLabel {\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tvBitacora = QtWidgets.QTableView(parent=Frame)
        self.tvBitacora.setStyleSheet("QTableView {\n"
"    margin: 16px\n"
"}")
        self.tvBitacora.setObjectName("tvBitacora")
        self.verticalLayout.addWidget(self.tvBitacora)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_4.setText(_translate("Frame", "Bitacora"))
