# Form implementation generated from reading ui file 'frame_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 588)
        MainWindow.setSizeIncrement(QtCore.QSize(500, 0))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.stackedWidget.setMouseTracking(True)
        self.stackedWidget.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(131, 131, 131);\n"
"    border-radius: 13px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(103, 164, 255)\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(260, 10, 251, 71))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuReportes = QtWidgets.QMenu(parent=self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuUtilidades = QtWidgets.QMenu(parent=self.menubar)
        self.menuUtilidades.setObjectName("menuUtilidades")
        self.menuEntidades = QtWidgets.QMenu(parent=self.menubar)
        self.menuEntidades.setObjectName("menuEntidades")
        self.menuTransacciones = QtWidgets.QMenu(parent=self.menubar)
        self.menuTransacciones.setObjectName("menuTransacciones")
        self.menuAyudas = QtWidgets.QMenu(parent=self.menubar)
        self.menuAyudas.setObjectName("menuAyudas")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSucursal = QtGui.QAction(parent=MainWindow)
        self.actionSucursal.setObjectName("actionSucursal")
        self.actionEmpleado = QtGui.QAction(parent=MainWindow)
        self.actionEmpleado.setObjectName("actionEmpleado")
        self.actionMunicipio = QtGui.QAction(parent=MainWindow)
        self.actionMunicipio.setObjectName("actionMunicipio")
        self.actionCargo = QtGui.QAction(parent=MainWindow)
        self.actionCargo.setObjectName("actionCargo")
        self.actionUsuario = QtGui.QAction(parent=MainWindow)
        self.actionUsuario.setObjectName("actionUsuario")
        self.actionProfesion = QtGui.QAction(parent=MainWindow)
        self.actionProfesion.setObjectName("actionProfesion")
        self.actionContrato = QtGui.QAction(parent=MainWindow)
        self.actionContrato.setObjectName("actionContrato")
        self.actionDepartamento = QtGui.QAction(parent=MainWindow)
        self.actionDepartamento.setObjectName("actionDepartamento")
        self.actionTipo_Municipio = QtGui.QAction(parent=MainWindow)
        self.actionTipo_Municipio.setObjectName("actionTipo_Municipio")
        self.actionListar_sucursales = QtGui.QAction(parent=MainWindow)
        self.actionListar_sucursales.setObjectName("actionListar_sucursales")
        self.actionInforme_empleados = QtGui.QAction(parent=MainWindow)
        self.actionInforme_empleados.setObjectName("actionInforme_empleados")
        self.actionBitacora = QtGui.QAction(parent=MainWindow)
        self.actionBitacora.setObjectName("actionBitacora")
        self.actionCalculadora = QtGui.QAction(parent=MainWindow)
        self.actionCalculadora.setObjectName("actionCalculadora")
        self.actionFecha_y_hora_actual = QtGui.QAction(parent=MainWindow)
        self.actionFecha_y_hora_actual.setObjectName("actionFecha_y_hora_actual")
        self.actionAyudas_de_la_aplicaci_n = QtGui.QAction(parent=MainWindow)
        self.actionAyudas_de_la_aplicaci_n.setObjectName("actionAyudas_de_la_aplicaci_n")
        self.actionAcerca_de = QtGui.QAction(parent=MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionVentana_Principal = QtGui.QAction(parent=MainWindow)
        self.actionVentana_Principal.setObjectName("actionVentana_Principal")
        self.actionLogout = QtGui.QAction(parent=MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.menuReportes.addAction(self.actionListar_sucursales)
        self.menuReportes.addAction(self.actionInforme_empleados)
        self.menuUtilidades.addAction(self.actionUsuario)
        self.menuUtilidades.addAction(self.actionBitacora)
        self.menuUtilidades.addAction(self.actionCalculadora)
        self.menuUtilidades.addAction(self.actionFecha_y_hora_actual)
        self.menuEntidades.addAction(self.actionDepartamento)
        self.menuEntidades.addAction(self.actionTipo_Municipio)
        self.menuEntidades.addAction(self.actionMunicipio)
        self.menuEntidades.addAction(self.actionSucursal)
        self.menuEntidades.addAction(self.actionCargo)
        self.menuEntidades.addAction(self.actionProfesion)
        self.menuEntidades.addAction(self.actionEmpleado)
        self.menuTransacciones.addAction(self.actionContrato)
        self.menuAyudas.addAction(self.actionAcerca_de)
        self.menuFile.addAction(self.actionVentana_Principal)
        self.menuFile.addAction(self.actionLogout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEntidades.menuAction())
        self.menubar.addAction(self.menuTransacciones.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuUtilidades.menuAction())
        self.menubar.addAction(self.menuAyudas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ventana Principal"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuUtilidades.setTitle(_translate("MainWindow", "Utilidades"))
        self.menuEntidades.setTitle(_translate("MainWindow", "Entidades"))
        self.menuTransacciones.setTitle(_translate("MainWindow", "Transacciones"))
        self.menuAyudas.setTitle(_translate("MainWindow", "Ayudas"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSucursal.setText(_translate("MainWindow", "Sucursal"))
        self.actionEmpleado.setText(_translate("MainWindow", "Empleado"))
        self.actionMunicipio.setText(_translate("MainWindow", "Municipio"))
        self.actionCargo.setText(_translate("MainWindow", "Cargo"))
        self.actionUsuario.setText(_translate("MainWindow", "Usuario"))
        self.actionProfesion.setText(_translate("MainWindow", "Profesion"))
        self.actionContrato.setText(_translate("MainWindow", "Contrato"))
        self.actionDepartamento.setText(_translate("MainWindow", "Departamento"))
        self.actionTipo_Municipio.setText(_translate("MainWindow", "Tipo Municipio"))
        self.actionListar_sucursales.setText(_translate("MainWindow", "Listar sucursales"))
        self.actionInforme_empleados.setText(_translate("MainWindow", "Informe empleados"))
        self.actionBitacora.setText(_translate("MainWindow", "Bitácora de usuarios"))
        self.actionCalculadora.setText(_translate("MainWindow", "Calculadora"))
        self.actionFecha_y_hora_actual.setText(_translate("MainWindow", "Fecha y hora actual"))
        self.actionAyudas_de_la_aplicaci_n.setText(_translate("MainWindow", "Ayudas de la aplicación"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de..."))
        self.actionVentana_Principal.setText(_translate("MainWindow", "Ventana Principal"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
