# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 588)
        MainWindow.setSizeIncrement(QtCore.QSize(500, 0))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(320, 10, 101, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuReportes = QtWidgets.QMenu(parent=self.menubar)
        self.menuReportes.setObjectName("menuReportes")
        self.menuUtilidades = QtWidgets.QMenu(parent=self.menubar)
        self.menuUtilidades.setObjectName("menuUtilidades")
        self.menuEntidades = QtWidgets.QMenu(parent=self.menubar)
        self.menuEntidades.setObjectName("menuEntidades")
        self.menuTransacciones = QtWidgets.QMenu(parent=self.menubar)
        self.menuTransacciones.setObjectName("menuTransacciones")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSucursal = QtGui.QAction(parent=MainWindow)
        self.actionSucursal.setObjectName("actionSucursal")
        self.actionEmpleado = QtGui.QAction(parent=MainWindow)
        self.actionEmpleado.setObjectName("actionEmpleado")
        self.actionMunicipio = QtGui.QAction(parent=MainWindow)
        self.actionMunicipio.setObjectName("actionMunicipio")
        self.actionCargo = QtGui.QAction(parent=MainWindow)
        self.actionCargo.setObjectName("actionCargo")
        self.actionUsuario = QtGui.QAction(parent=MainWindow)
        self.actionUsuario.setObjectName("actionUsuario")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuEntidades.addAction(self.actionSucursal)
        self.menuEntidades.addAction(self.actionEmpleado)
        self.menuEntidades.addAction(self.actionMunicipio)
        self.menuEntidades.addAction(self.actionCargo)
        self.menuEntidades.addAction(self.actionUsuario)
        self.menuEntidades.addAction(self.actionSalir)
        self.menubar.addAction(self.menuEntidades.menuAction())
        self.menubar.addAction(self.menuTransacciones.menuAction())
        self.menubar.addAction(self.menuReportes.menuAction())
        self.menubar.addAction(self.menuUtilidades.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ventana Principal"))
        self.menuReportes.setTitle(_translate("MainWindow", "Reportes"))
        self.menuUtilidades.setTitle(_translate("MainWindow", "Utilidades"))
        self.menuEntidades.setTitle(_translate("MainWindow", "Entidades"))
        self.menuTransacciones.setTitle(_translate("MainWindow", "Transacciones"))
        self.actionSucursal.setText(_translate("MainWindow", "Sucursal"))
        self.actionEmpleado.setText(_translate("MainWindow", "Empleado"))
        self.actionMunicipio.setText(_translate("MainWindow", "Municipio"))
        self.actionCargo.setText(_translate("MainWindow", "Cargo"))
        self.actionUsuario.setText(_translate("MainWindow", "Usuario"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
